include:
  - board: nice_nano@2.0.0//zmk
    shield: Lily58_L Nice_view_config nice_view nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Lily58_left_nice_view
  - board: nice_nano@2.0.0//zmk
    shield: Lily58_R Nice_view_config nice_view nice_view_custom
    artifact-name: Lily58_right_nice_view

  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
